function [applic_boolean,BOUNDARY_CONDITIONS_MATRIX  , acsolio , acsolmo ,...
        bc , bcbot_changed , bctop_changed , boco_bot , boco_bot_type , boco_top , boco_top_type ,...
        bot_flux , bot_inf , carblit , carbman, cden , chyd , cim , cm , cm_node , cm_profile ,...
        cmin , cnit , conirsol , cs , csol , cum_bot_flxs , cum_evap , cum_infiltr , cum_nit_sink ,...
        cum_pot_transp , cum_potential_surface_flux , cum_sink_wat , cum_sink_wat2 , cum_top_flxs , cum_trans , cupt , cvol , ddepsol ,...
        deccorg , decnorg , deniti , denitm , diffus , drz , drza , dt , dt_changed_bc , dt_sol_count,...
        evap , first_time , first_time_bc , flxar , flxsa , flxsah , flxsbot , ...
        front , fsol , hydro_ureai , hydro_uream ,...
        iter , miner_param , mineri , minerm ,  next_dt_new_bc , nitrifi , nitrifm ,...
        om_appl , om_balance , om_node , om_param , om_profile,ph , ph_node , ph_profile , phbot , phsa ,....
        phsurf, pond , pond_from , ponded , potential_surface_flux , potential_transp , ppdepth ,...
        ptden , pthyd , ptmin , ptnit , ptscorg , ptsnorg , ptup , ptvol , pvela , pvelah , pvelo , pveloh ,...
        reservoir , rleasa , rnitlit , rnitman , root_dens_time , root_density_time2 , root_density_time3,root_length_time ,...
        runoff , seep, sink , snode , soil_om , solute_balance , t , tc_node , tc_profile , tcorgs , tcsink , tcsolo , tcsolo_ini , temp , temp_node ,...
        temp_profile , temptopp , tflcorg , tflnorg , tflsol , time_uptake, tnode , tnorgs , top_flux , top_inf , tot_upt , trans ,...
        tsoli, uptake_matrix , uptakei , uptakem , volati , volatm , wat_flxs , wat_flxsa , water_storage , wc_node , wc_profile ,...
        wcio , wciob , wcma , wcmah , wcmo , wcmob , wco , wcob , wcp , wdepsol,initsol,und,unc,rtex,wat_flxsah,diffush]=...
        runwave(BOUNDARY_CONDITIONS_MATRIX  , Smax_given , Smax_param , acsolio , acsolmo ,...
        applic_boolean,arel , bc , bcbot_changed , bctop_changed , boco_bot , boco_bot_type , boco_top , boco_top_type ,...
        bot_flux , bot_inf , brel , carblit , carbman  , cden , chyd , cim , cm , cm_node , cm_profile ,...
        cmin , cnit , column_depth , compartiments_number , conirsol , cs , csol , cum_bot_flxs , cum_evap , cum_infiltr , cum_nit_sink ,...
        cum_pot_transp , cum_potential_surface_flux , cum_sink_wat , cum_sink_wat2 , cum_top_flxs , cum_trans , cupt , cvol , ddepsol ,...
        deccorg , decnorg , deniti , denitm , diffus , drz , drza , dt , dt_changed_bc , dt_max , dt_min , dt_sol_count , dt_start , dx ,...
        dx_inter , epa , err_tol , esa , evap , first_time , first_time_bc , flxar , flxsa , flxsah , flxsbot , ...
        front , fsol , harvest_date , hs , hydro_ureai , hydro_uream , idvs , immobile , initial_gwl ,...
        isucr , iter , maxiter , miner_param , mineri , minerm , ncbot , ncomp , ncs , next_dt_new_bc , nitrifi , nitrifm ,...
        nsol , om_appl , om_balance , om_node , om_param , om_profile , output_crop , ph , ph_node , ph_profile , phbot , phsa ,....
        phsurf , plant_date , plant_uptake_param , pond , pond_from , ponded , potential_surface_flux , potential_transp , ppdepth ,...
        print_node , print_time , ptden , pthyd , ptmin , ptnit , ptscorg , ptsnorg , ptup , ptvol , pvela , pvelah , pvelo , pveloh ,...
        reservoir , rleasa , rnitlit , rnitman , root_dens_time , root_density_time2 , root_density_time3 ,...
        runoff , seep , sim_nitro , simplant , simsol , simtemp , sink , snode , soil_om , soil_parameters , solute_balance , solute_param1 ,...
        solute_param2 , stock_initial , stock_max , t , tc_node , tc_profile , tcorgs , tcsink , tcsolo , tcsolo_ini , temp , temp_node ,...
        temp_profile , temptopp , tflcorg , tflnorg , tflsol , time_uptake , tmax , tnode , tnorgs , top_flux , top_inf , tot_upt , trans ,...
        tsoli , units , uptake_matrix , uptakei , uptakem , volati , volatm , wat_flxs , wat_flxsa , water_storage , wc_node , wc_profile ,...
        wcio , wciob , wcma , wcmah , wcmo , wcmob , wco , wcob , wcp , wdepsol,NDemand,PLM2,PropFact,root_length_time,initsol,solboco_input_type,RLengthLa,...
        fraction_time,rdens,crop_type,ncrop);
    
% Evaluate bc at time t and t+dt, chooses right bc, checks if bc 
    % changed during previous iteration
    var_changed =[bctop_changed,bcbot_changed,dt_changed_bc,next_dt_new_bc,first_time_bc];
%     
    [hs,phsa,flxar,flxa1,boco_top_type,boco_top,boco_bot_type,boco_bot,pond,...
        bctop_changed,bcbot_changed,first_time_bc,dt_changed_bc,next_dt_new_bc,phsurf,esa,...
        BOUNDARY_CONDITIONS_MATRIX,ncbot]=...
        soil_boundary_conditions_new(var_changed,t,ph,dt,phsurf,flxar,boco_top_type,...
        boco_top,boco_bot_type,boco_bot,pond,runoff,simplant,dt_min,dt_start,...
        BOUNDARY_CONDITIONS_MATRIX,esa,hs,phsa,ncbot,dx_inter,ncs,arel,brel,plant_date,harvest_date);
    
    % Calculate ph
	[ph,wat_flxs,dt,iter,runoff,no_conv,WC,bctop_changed,bcbot_changed,pond,...
        phsurf,flxar,boco_top_type,boco_bot_type,rtex,EPRA,boco_top] =...
        solve_flow(ph,t,dt,compartiments_number,iter,boco_top_type,boco_top,boco_bot_type,...
        boco_bot,pond,flxa1,dt_start,dx,dx_inter,stock_max,seep,soil_parameters,ponded,pond_from,...
        hs,phsa,maxiter,dt_min,phsurf,phbot,flxsbot,flxar,bctop_changed,bcbot_changed,err_tol,simplant,...
        units,plant_date,harvest_date,ncbot,drz,epa);      
    
      %Calculate temperature
      if simtemp
        [temp, temptopp] = solve_temperature_JV(dt, dx, ncomp, t, WC, wcp, temp, soil_parameters,temptopp,tmax,units,solute_param1);
      end                 
      
      
      %Calculate solute
     if simsol
        [wat_flxsa, wat_flxsah, pvela, pvelah, pveloh,pvelo, wcio, wciob, wcma, wcmah,wcmob, wcmo, wco, wcob,diffus,diffush,initsol]=...
         wat_sol(t,wat_flxs, wat_flxsa, immobile, ncs,solute_param1,solute_param2,pvela,WC, wcio, wcma,wcmo, wco,pvelo,diffus,nsol,dx,initsol);
            
        [cs,csp,cm,cim,cmp,cimp,csol,soil_om,sol_sinkm,sol_sinki,tot_upt,acsolo,acsolio,acsolmo,sflxsa,...
            ddepsol, wdepsol, fsol, conirsol, ppdepth,reservoir,first_time,uptake_matrix,uptakem,...
            solute_applic,uptakei,minerm,mineri,nitrifm,nitrifi,denitm,deniti,hydro_uream,hydro_ureai,...
            volatm,volati,decnorg,deccorg,carbman,carblit,rnitman,rnitlit,om_appl,und,unc,rdens]=...
        solve_solute(t,dt,tmax,temp,dx,nsol,ncs,WC,rtex,cm,cim,csol,cs,acsolmo,acsolio,wat_flxs,ph,...
                    wat_flxsa, wat_flxsah,wcio, wciob, wcma, wcmah, wcmo, wcmob,wco,wcob,pvela,pvelah,...
                    pveloh,soil_om,immobile,soil_parameters,solute_param1,solute_param2,...
                    om_param,miner_param, plant_uptake_param, tot_upt,sim_nitro,tcsolo_ini,diffush,...
                    plant_date,harvest_date,isucr,simplant,ddepsol, wdepsol, fsol, conirsol,...
                    ppdepth,reservoir,tcsolo,first_time,om_appl,drz,NDemand,PLM2,PropFact,initsol,solboco_input_type,RLengthLa,fraction_time,rdens,ncrop);

        [cberr_sol,tflsol,rleasa,tcsink,tsoli,tcsolo_ini,dsol,tcsolo,initsol]=sol_intgr(t,dt,dx,nsol,ncs,cm,cim,cmp,cimp,csol,wcmo,wcio,wcob,wco,solute_param1,...
            solute_param2,sol_sinki,sol_sinkm,acsolmo,acsolio,acsolo,sflxsa,tflsol,rleasa,tsoli,tcsink,tcsolo_ini,immobile,initsol);
        
                  if sim_nitro
              [ptsnorg, ptscorg, ptup, cupt, pthyd, chyd, ptnit, cnit, ptvol, cvol, ptden, cden,...
                dnorg, dcorg, cberr_norg, cberr_corg,tflnorg,tflcorg,ptmin,cmin,om_balance] = ...
                nit_intg(ptsnorg,ptscorg, ptup, cupt, ptmin, cmin, pthyd, chyd, ptnit, cnit, ptvol,...
                 cvol, ptden, cden, soil_om,tcorgs,tnorgs,carbman,carblit,rnitman,rnitlit,decnorg,deccorg,...
                 uptakem,uptakei,minerm,mineri,nitrifm,nitrifi,denitm,deniti,hydro_uream,hydro_ureai,...
                volatm,volati,tflnorg,tflcorg,dx,dt,om_balance);
                  end

     end



     
     % Calculate output data
[delta_stock,mass_balance_error, cum_top_flxs, cum_bot_flxs, cum_sink_wat, cum_sink_wat2,sink_prof] = ...
   wat_intgr(ph,wat_flxs,cum_top_flxs ,cum_bot_flxs,cum_sink_wat, cum_sink_wat2, stock_initial,dt,dx,...
   compartiments_number,soil_parameters,rtex);
	% Display information
%   	disp([t,dt,iter,boco_top_type,boco_top]);
    % Store data for model output 
[wc_profile,tnode,wc_node,ph_node,bot_flux,top_flux,top_inf,snode,evap,trans,sink,ph_profile,bot_inf, potential_surface_flux, cum_potential_surface_flux, potential_transp, cum_evap, cum_infiltr,cum_pot_transp,cum_trans,water_storage] = store_data(t,ph,...
   wc_profile,tnode,ph_node,wc_node,print_time,print_node,cum_bot_flxs,cum_top_flxs,...
   bot_flux,top_flux,no_conv,WC,wat_flxs,top_inf,esa,cum_sink_wat,snode,evap,trans,sink_prof,sink,ph_profile,bot_inf, potential_surface_flux, cum_potential_surface_flux, potential_transp, cum_evap, cum_infiltr,flxar,dt,epa,cum_pot_transp,cum_trans,cum_sink_wat2,simplant,water_storage,dx);

if simsol
    %store Concentration
[cm_profile,cm_node]=store_CM(print_time,...
    print_node,cm,no_conv,t,cm_profile,cm_node,wc_profile,nsol,simsol);
    %Store organic matter pools
[om_profile,om_node]=store_om(print_time,...
    print_node,soil_om,no_conv,t,om_profile, om_node,sim_nitro);
%Store absolute values of solute
[tc_profile,tc_node]=store_tc(print_time,...
   print_node,tcsolo,no_conv,t,tc_profile,tc_node,nsol,simsol);
%Store Mass balance information for the solutes.
solute_balance = store_solute_balance(cberr_sol,tflsol,rleasa,tcsink,tsoli,tcsolo_ini,dsol,tcsolo,solute_balance,t,nsol,dt);
    
    if sim_nitro
        [cum_nit_sink] = store_nit(ptsnorg, ptscorg,ptup, cupt, pthyd, chyd, ptnit, cnit, ptvol, cvol, ptden, cden,...
            dnorg, dcorg, cberr_norg, cberr_corg,tflnorg,tflcorg,ptmin,cmin, cum_nit_sink);
    end
    
end

if simplant
    %Store uptake terms
    time_uptake(end+1,1:7) = [uptake_matrix NDemand];
    %Store root information
        root_length_time (end+1) = [drza];
        root_dens_time(end+1,:) = rdens;
        root_density_time2 (end+1,:) = uptakem(:,2);
        root_density_time3 (end+1,:) = uptakem(:,3);
end


if simtemp
    [temp_node, temp_profile]=store_T(print_time,...
    print_node,no_conv,t, temp, temp_profile, temp_node);
end

% Calculation of delta t
   	t=t+dt; 
    [dt,dt_changed_bc]=calc_dt_new(t,dt,iter,dt_min,dt_max,BOUNDARY_CONDITIONS_MATRIX,rtex, wat_flxs,dx,ncs);
    if simsol
    [dt_sol,applic_boolean,dt_sol_count] = calc_dt_sol(t,nsol,dt, applic_boolean,dt_min, units,cs,csp,dt_sol_count,dx,reservoir,fsol, conirsol,wdepsol,ddepsol);
    else
    dt_sol = dt;
    end
    dt = min(dt, dt_sol);
    
% Evaluate bc
    bc(end+1,:)=[t,boco_top_type,boco_top,boco_bot_type,boco_bot,pond,runoff,flxa1,dt,iter];
   
    % Break when no convergence is reached
    if no_conv
        disp('No convergence');
        return
    end
