function [immobile,simsol,sim_nitro,sim_temp,simplant,isucr,idvs,column_depth,compartiments_number,t,tmax,dt_start,dt_min,...
    dt_max,maxiter,err_tol,plant_date,crop_type,harvest_date,...
    plant_uptake_param,miner_param,nsol,PLM2] = read_inputfile(scenario_number, scenario_file)

% scenario_file= ('input_1punt.xlsx');
scenario_number = 1;
%Read datafile
input_dataset = xlsread(scenario_file)

%Select the correct line to be used as an input

[immobile,simsol,sim_nitro,sim_temp,simplant,isucr,idvs,column_depth,compartiments_number,t,tmax,dt_start,dt_min,...
    dt_max,maxiter,err_tol, rorad,rd0,g	,rnmaxp,rdens0,alfardens,r0,fe,fh,nsol]=...
    deal(...
    input_dataset(scenario_number,1), input_dataset(scenario_number,2),...
    input_dataset(scenario_number,3),input_dataset(scenario_number,4),...
    input_dataset(scenario_number,5),input_dataset(scenario_number,6),...
    input_dataset(scenario_number,7), input_dataset(scenario_number,8),...
    input_dataset(scenario_number,9),input_dataset(scenario_number,10),...
    input_dataset(scenario_number,11),input_dataset(scenario_number,12),...
    input_dataset(scenario_number,13),input_dataset(scenario_number,14),...
    input_dataset(scenario_number,15),input_dataset(scenario_number,16),...
    input_dataset(scenario_number,17), input_dataset(scenario_number,18),...
    input_dataset(scenario_number,19),input_dataset(scenario_number,20),...
    input_dataset(scenario_number,21),input_dataset(scenario_number,22),...
    input_dataset(scenario_number,23),input_dataset(scenario_number,24),...
    input_dataset(scenario_number,25),input_dataset(scenario_number,26) )

%Retrieve plant and harvest dates
number_crops = (size(input_dataset,2)-26)/4;
for i=1:number_crops
    plant_date(i) = input_dataset(scenario_number, 26+i);
    crop_type(i) = input_dataset(scenario_number, 26+number_crops+i);
    harvest_date(i) = input_dataset(scenario_number, 26+2*number_crops+i);
    PLM2(i)= input_dataset(scenario_number, 26+3*number_crops+i);
end

% Combine some parameters into one variable
plant_uptake_param = [rorad, rd0, g, rnmaxp, rdens0, alfardens];
miner_param = [r0, fe, fh];
